version: '3'

services:
  db:
    image: postgres:12.2-alpine
    environment:
      POSTGRES_DB: nice_marmot
      POSTGRES_USER: runner
      POSTGRES_PASSWORD: ""
      POSTGRES_HOST_AUTH_METHOD: trust
  web:
    build: .
    command: python /code/djangoweb/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
