version: '3'

services:
  db:
    image: postgres:12.2-alpine
    restart: always
    environment:
      POSTGRES_DB: nice_marmot
      POSTGRES_USER: runner
      POSTGRES_PASSWORD: ""
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5433:5432
  web:
    build: .
    command: bash -c "
        pip install requests
        && mkdir /shared/plotting
        && mkdir /shared/machinelearning
        && python manage.py makemigrations api
        && python manage.py collectstatic
        && python /code/djangoweb/manage.py runserver 0.0.0.0:8080
      "
    volumes:
      - .:/code
      - ./shared:/shared
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - db
  node_auth_server:
    build: ./node_auth_server
    image: node:latest
    restart: always
    command: bash -c "
      cd /node_auth_server
      && npm install
      && npm install bcrypt
      && npm run migrate
      && npm start
      "
    volumes:
      - ./node_auth_server:/node_auth_server
      - ./shared:/shared
    ports:
      - 8090:8090
  basicanalysis:
    build: ./basicanalysis
    image: alikth/basic_cell:latest
    restart: always
    command: bash -c "
        pip install -r requirements.txt
        && python3.6 api.py
      "
    volumes:
      - ./basicanalysis:/usr/src/app
      - ./shared:/shared
    ports:
      - 3000:3000
    depends_on:
      - web
  plotting:
    build: ./plotting
    image: alikth/basic_cell:latest
    restart: always
    command: bash -c "
        pip install -r requirements.txt
        && python3.6 api.py
      "
    volumes:
      - ./plotting:/usr/src/app
      - ./shared:/shared
    ports:
      - 4000:4000
    depends_on:
      - web
  machinelearning:
    build:
      context: ./machinelearning
    image:  alikth/ml_cell:latest
    restart: always
    command: bash -c "
      pip install -r requirements.txt
      && pip3 uninstall bottleneck -y
      && pip3 install bottleneck==1.2
      && python3.6 api.py
      "
    volumes:
      - ./machinelearning:/usr/src/app
      - ./shared:/shared
    ports:
      - 5000:5000
    depends_on:
      - web
