version: '3'

services:
  db:
    image: postgres:12.2-alpine
    environment:
      POSTGRES_DB: nice_marmot
      POSTGRES_USER: runner
      POSTGRES_PASSWORD: ""
      POSTGRES_HOST_AUTH_METHOD: trust
  web:
    build: .
    command: bash -c "
        python /code/djangoweb/manage.py runserver 0.0.0.0:8000
        && python3.6 manage.py makemigrations api
        && python3.6 manage.py collectstatic
      "
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
